### ISSUE TITLE
Allow a way for the rate limiter to return error without blocking if enough tokens are not available

### ISSUE THREAD

**Issue by niks3089** [udoprog/leaky-bucket#20] opened 2024-05-14 15:45 UTC
Instead of waiting on tokens to be available, is there a way to return an error immediately? We don't want to check the balance and request the available number of tokens but would like to return an error immediately and the application can try again later

**Comment by udoprog** [comment] 2024-05-14 18:05
So something like this?

```rust
if !limiter.try_acquire(100) {
    return Err(..);
}
```

How would you like it to behave if there are tasks waiting for tokens?

For a [fair scheduler](https://docs.rs/leaky-bucket/latest/leaky_bucket/#fairness) I believe the "correct" behavior under that scenario should be for `try_acquire` to return `false`, since there are tasks ahead which takes priority. Does this sound right to you?

**Comment by udoprog** [comment] 2024-05-15 01:13
There is an implementation in git now if you want to give it a try and report back.

**Comment by niks3089** [comment] 2024-05-15 05:00
Thanks, will give it a test. I see that `try_acquire` returns true if there's enough tokens. Can we change that to actually acquire the tokens. With current `try_acquire`, its going be like this 

```
if !limiter.try_acquire(100) {
    return Err(..);
}
limiter.acquire(100)
```

Instead can we do the above in the same `try_acquire`?

**Comment by udoprog** [comment] 2024-05-15 05:21
Ah. That's actually how `try_acquire` works, the documentation was a bit fuzzy, so I fixed that.

**Comment by niks3089** [comment] 2024-05-15 07:16
Awesome, thanks. I will give it a test over the weekend and update

**Comment by niks3089** [comment] 2024-05-21 11:18
Sorry, didn't get time to test this. Will test and update asap this week

**Comment by niks3089** [comment] 2024-05-22 17:47
@udoprog, I am seeing this behaviour for this code 

```
        let limiter = LeakyRateLimiter::builder()
            .initial(group.global_max_burst.get() as usize)
            .refill(group.request_per_second.get() as usize)
            .interval(Duration::from_millis(1000))
            .max(group.global_max_burst.get() as usize)
            .build();
 ```
 The rps is am setting is 500 with max burst being 1500. When I test with `limiter.try_acquire` of lets say as large number of `10000`, I get false but after sometime, when I test again, I get true which seems like the bucket keeps accumulating tokens beyond `max` which seems like a bug. I would assume any request beyond `max` should return false always

**Comment by udoprog** [comment] 2024-05-22 18:51
Ah, yeah. It seems I reproduced an existing issue that I've already fixed in the async version when implementing `try_acquire`.

[This part here](https://github.com/udoprog/leaky-bucket/blob/main/src/lib.rs#L750) should actually be doing this:

```rust
state.balance = state.balance.saturating_add(tokens).min(self.max);
```

**Comment by niks3089** [comment] 2024-05-25 05:59
Been testing for couple of days and it's working great. Feel free to close the ticket. Thanks for the quick turnaround

**Closed** 2024-05-25 11:04 UTC
Labels: enhancement
